spring.data.mongodb.uri=mongodb://localhost:27017/your_database
server.port=8081
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/your-realm
jwt.auth.converter.principal-attribute=preferred_username
jwt.auth.converter.resource-id=your-client-id
keycloak.realm=your-realm
keycloak.auth-server-url=http://localhost:8080
keycloak.resource=your-client-id
keycloak.public-client=true
keycloak.bearer-only=true
